# Generated by Django 6.0.1 on 2026-01-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='static_image',
            field=models.CharField(blank=True, help_text='Static image filename (e.g., shirt.jpg)', max_length=200),
        ),
    ]
