# Generated by Django 6.0.1 on 2026-01-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_orderitem_size_product_available_sizes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available_sizes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='has_sizes',
        ),
        migrations.AddField(
            model_name='product',
            name='size_type',
            field=models.CharField(choices=[('none', 'No Size'), ('clothing', 'Clothing (XS, S, M, L, XL, 2XL)'), ('shoe', 'Shoe (36, 37, 38, 39, 40, 41, 42, 43)')], default='none', help_text='Select size type for this product', max_length=20),
        ),
    ]
